apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-kube-state-metrics
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: resources/kube-state-metrics/overlays/staging
    repoURL: https://github.com/meziaris/K8S-MANIFEST.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
